2024-05-29 11:20:49,969 [WARNING] USER:Berkay_Buharali __init__.py:190:initialize_project_state LOG: [93mConfig is set and generated but project state does not exist, seems that you've come from the previous version.[0m
2024-05-29 11:20:49,969 [WARNING] USER:Berkay_Buharali __init__.py:193:initialize_project_state LOG: [93mGenerating project state file (.syndicate) from the existing structure...[0m
2024-05-29 11:20:49,971 [INFO] USER:Berkay_Buharali helper.py:588:check_lambda_name LOG: Validating lambda name: 'task01'
2024-05-29 11:20:49,971 [INFO] USER:Berkay_Buharali helper.py:603:check_lambda_name LOG: Lambda name: 'task01' passed the validation
2024-05-29 11:20:49,972 [INFO] USER:Berkay_Buharali project.py:90:_generate_java_project_hierarchy LOG: Generating pom inside /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/BbAwsServerlessTask01
2024-05-29 11:20:49,972 [INFO] USER:Berkay_Buharali project.py:95:_generate_java_project_hierarchy LOG: Pom file was generated by path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/BbAwsServerlessTask01/pom.xml
2024-05-29 11:20:49,973 [INFO] USER:Berkay_Buharali lambda_function.py:319:_generate_java_lambdas LOG: Lambda task01 created
2024-05-29 11:20:49,974 [INFO] USER:Berkay_Buharali lambda_function.py:146:generate_lambda_function LOG: Lambda task01 has been successfully added to the project.
2024-05-29 11:20:49,974 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage lambda_function, elapsed time: 0:00:00.002641
2024-05-29 11:21:08,102 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:21:08,499 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage test, elapsed time: 0:00:00.000276
2024-05-29 11:21:08,504 [INFO] USER:Berkay_Buharali project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/jsrc/main/java/com/task01.
2024-05-29 11:21:08,504 [INFO] USER:Berkay_Buharali project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/src/lambdas.
2024-05-29 11:21:08,504 [INFO] USER:Berkay_Buharali project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/app/lambdas.
2024-05-29 11:21:08,504 [INFO] USER:Berkay_Buharali project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/swagger_src.
2024-05-29 11:21:08,504 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage assemble, elapsed time: 0:00:00.000417
2024-05-29 11:21:08,505 [INFO] USER:Berkay_Buharali meta_processor.py:483:create_meta LOG: Bundle path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/bundles/task01_240529.112108
2024-05-29 11:21:08,507 [INFO] USER:Berkay_Buharali helper.py:299:write_content_to_file LOG: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/.syndicate-config-dev/bundles/task01_240529.112108/build_meta.json file was created.
2024-05-29 11:21:08,507 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage package_meta, elapsed time: 0:00:00.001560
2024-05-29 11:21:08,625 [INFO] USER:Berkay_Buharali bundle_processor.py:185:upload_bundle_to_s3 LOG: Bundle was validated successfully
2024-05-29 11:21:08,708 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage upload, elapsed time: 0:00:00.163735
2024-05-29 11:21:08,710 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage build, elapsed time: 0:00:00.444935
2024-05-29 11:21:21,991 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:21:22,216 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:21:22,216 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:21:22,346 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:21:22,346 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: task01
2024-05-29 11:21:22,441 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:21:22,441 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:21:22,554 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:21:22,554 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: task01_240529.112108
2024-05-29 11:21:22,641 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:21:22,641 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:21:22,751 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:21:22,847 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:21:22,848 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:21:22,967 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:21:23,190 [ERROR] USER:Berkay_Buharali helper.py:84:wrapper LOG: An error occurred. See details in the log file
2024-05-29 11:21:23,190 [ERROR] USER:Berkay_Buharali helper.py:85:wrapper LOG: Error occurred: Deployment output file not found. It might be because the previous deployment failed. If this is the case deployment can be continued by using the command  'syndicate deploy --continue_deploy' or failed deployed resources can be removed with the command 'syndicate clean --rollback'
Traceback (most recent call last):
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/build/bundle_processor.py", line 140, in load_latest_deploy_output
    return load_deploy_output(bundle_name, deploy_name)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/build/bundle_processor.py", line 111, in load_deploy_output
    raise AssertionError('Deploy name {0} does not exist.'
AssertionError: Deploy name aws-serverless does not exist. Cannot find output file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/helper.py", line 82, in wrapper
    return handler_func(*args, **kwargs)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/build/deployment_processor.py", line 298, in create_deployment_resources
    latest_deploy_output = load_latest_deploy_output()
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/build/bundle_processor.py", line 143, in load_latest_deploy_output
    raise AssertionError(
AssertionError: Deployment output file not found. It might be because the previous deployment failed. If this is the case deployment can be continued by using the command  'syndicate deploy --continue_deploy' or failed deployed resources can be removed with the command 'syndicate clean --rollback'
2024-05-29 11:21:23,330 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:21:23,331 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:21:23,462 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:22:11,755 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:22:12,052 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:22:12,052 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:22:12,200 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:22:12,200 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: aws-serverless
2024-05-29 11:22:12,295 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:22:12,295 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:22:12,393 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:22:12,393 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: AWS_Serverless_240528.140655
2024-05-29 11:22:12,481 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:22:12,481 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:22:12,581 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:22:12,680 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:22:12,680 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:22:12,785 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:22:12,869 [INFO] USER:Berkay_Buharali deployment_processor.py:564:remove_failed_deploy_resources LOG: Failed output file was loaded successfully
2024-05-29 11:22:12,869 [INFO] USER:Berkay_Buharali deployment_processor.py:568:remove_failed_deploy_resources LOG: Prefixes and suffixes of any resource names have been resolved.
2024-05-29 11:22:12,869 [INFO] USER:Berkay_Buharali deployment_processor.py:597:remove_failed_deploy_resources LOG: Going to clean AWS resources
2024-05-29 11:22:12,869 [INFO] USER:Berkay_Buharali deployment_processor.py:176:clean_resources LOG: Removing iam_role resources ...
2024-05-29 11:22:15,305 [INFO] USER:Berkay_Buharali iam_resource.py:82:_remove_role LOG: IAM role cmtr-5203d48b-hello-lambda-role was removed.
2024-05-29 11:22:15,429 [INFO] USER:Berkay_Buharali iam_resource.py:82:_remove_role LOG: IAM role cmtr-5203d48b-PutObjectToS3Role was removed.
2024-05-29 11:22:15,430 [INFO] USER:Berkay_Buharali deployment_processor.py:176:clean_resources LOG: Removing iam_policy resources ...
2024-05-29 11:22:15,824 [INFO] USER:Berkay_Buharali iam_resource.py:46:_remove_policy LOG: IAM policy cmtr-5203d48b-lambda-basic-execution was removed.
2024-05-29 11:22:15,846 [INFO] USER:Berkay_Buharali iam_resource.py:46:_remove_policy LOG: IAM policy cmtr-5203d48b-LambdaBasicExecution was removed.
2024-05-29 11:22:16,146 [INFO] USER:Berkay_Buharali iam_resource.py:46:_remove_policy LOG: IAM policy cmtr-5203d48b-PutObjectToS3Policy was removed.
2024-05-29 11:22:16,170 [INFO] USER:Berkay_Buharali iam_resource.py:46:_remove_policy LOG: IAM policy cmtr-5203d48b-lambda-basic-execution2 was removed.
2024-05-29 11:22:16,171 [INFO] USER:Berkay_Buharali deployment_processor.py:183:clean_resources LOG: Removing dynamodb_table resources ...
2024-05-29 11:22:36,460 [INFO] USER:Berkay_Buharali dynamo_db_resource.py:402:remove_dynamodb_tables LOG: Dynamo DB tables ['cmtr-5203d48b-Notifications'] were removed
2024-05-29 11:22:36,836 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage clean, elapsed time: 0:00:24.048495
2024-05-29 11:22:36,908 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:22:36,908 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:22:37,190 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:22:37,191 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:22:37,295 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:22:47,519 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:22:47,792 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:22:47,792 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:22:47,922 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:22:47,923 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: task01
2024-05-29 11:22:48,020 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:22:48,020 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:22:48,158 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:22:48,158 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: task01_240529.112108
2024-05-29 11:22:48,255 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:22:48,255 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:22:48,359 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:22:48,462 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:22:48,462 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:22:48,560 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:22:48,770 [INFO] USER:Berkay_Buharali deployment_processor.py:312:create_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved.
2024-05-29 11:22:48,771 [INFO] USER:Berkay_Buharali deployment_processor.py:345:create_deployment_resources LOG: Going to deploy AWS resources
2024-05-29 11:22:49,161 [INFO] USER:Berkay_Buharali deployment_processor.py:85:_process_resources LOG: Processing iam_policy resources
2024-05-29 11:22:49,829 [INFO] USER:Berkay_Buharali iam_resource.py:118:_create_policy_from_meta LOG: Created IAM policy cmtr-5203d48b-lambda-basic-execution.
2024-05-29 11:22:49,997 [INFO] USER:Berkay_Buharali deployment_processor.py:97:_process_resources LOG: Processing iam_role resources
2024-05-29 11:22:53,317 [INFO] USER:Berkay_Buharali iam_resource.py:178:_create_role_from_meta LOG: Created IAM role cmtr-5203d48b-task01-role.
2024-05-29 11:22:53,318 [INFO] USER:Berkay_Buharali deployment_processor.py:348:create_deployment_resources LOG: AWS resources were deployed successfully
2024-05-29 11:22:53,318 [INFO] USER:Berkay_Buharali deployment_processor.py:351:create_deployment_resources LOG: Going to apply dynamic changes
2024-05-29 11:22:53,319 [INFO] USER:Berkay_Buharali deployment_processor.py:353:create_deployment_resources LOG: Dynamic changes were applied successfully
2024-05-29 11:22:53,319 [INFO] USER:Berkay_Buharali deployment_processor.py:355:create_deployment_resources LOG: Going to apply common tags
2024-05-29 11:22:53,352 [INFO] USER:Berkay_Buharali group_tagging_api_resource.py:62:apply_tags LOG: No tags are specified in config. Skipping...
2024-05-29 11:22:53,352 [INFO] USER:Berkay_Buharali deployment_processor.py:358:create_deployment_resources LOG: Going to create deploy output
2024-05-29 11:22:53,461 [INFO] USER:Berkay_Buharali bundle_processor.py:63:create_deploy_output LOG: Output file with name task01_240529.112108/outputs/task01.json has been created
2024-05-29 11:22:53,461 [INFO] USER:Berkay_Buharali deployment_processor.py:364:create_deployment_resources LOG: Deploy output for task01 was created.
2024-05-29 11:22:53,462 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage deploy, elapsed time: 0:00:04.739724
2024-05-29 11:22:53,593 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:22:53,593 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:22:53,717 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:24:48,232 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:24:48,501 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:24:48,502 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:24:48,622 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:24:48,622 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: task01
2024-05-29 11:24:48,722 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:24:48,722 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:24:48,836 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:24:48,837 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: task01_240529.112108
2024-05-29 11:24:48,934 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:24:48,935 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:24:49,037 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:24:49,142 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:24:49,142 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:24:49,255 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:24:49,287 [ERROR] USER:Berkay_Buharali helper.py:84:wrapper LOG: An error occurred. See details in the log file
2024-05-29 11:24:49,287 [ERROR] USER:Berkay_Buharali helper.py:85:wrapper LOG: Error occurred: Deploy name task01 does not exist. Cannot find output file.
Traceback (most recent call last):
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/helper.py", line 82, in wrapper
    return handler_func(*args, **kwargs)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/build/deployment_processor.py", line 563, in remove_failed_deploy_resources
    output = new_output = load_failed_deploy_output(bundle_name, deploy_name)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/build/bundle_processor.py", line 129, in load_failed_deploy_output
    raise AssertionError('Deploy name {0} does not exist.'
AssertionError: Deploy name task01 does not exist. Cannot find output file.
2024-05-29 11:24:49,395 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:24:49,395 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:24:49,500 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:25:29,878 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:25:30,091 [INFO] USER:Berkay_Buharali bundle_processor.py:207:create_bundles_bucket LOG: Bundles bucket syndicate-education-platform-custom-sandbox-artifacts-sbox01 already exists
2024-05-29 11:25:30,091 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage create_deploy_target_bucket, elapsed time: 0:00:00.213186
2024-05-29 11:25:39,210 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:25:39,508 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage test, elapsed time: 0:00:00.000133
2024-05-29 11:25:39,532 [INFO] USER:Berkay_Buharali project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/jsrc/main/java/com/task01.
2024-05-29 11:25:39,532 [INFO] USER:Berkay_Buharali project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/src/lambdas.
2024-05-29 11:25:39,532 [INFO] USER:Berkay_Buharali project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/app/lambdas.
2024-05-29 11:25:39,532 [INFO] USER:Berkay_Buharali project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/swagger_src.
2024-05-29 11:25:39,532 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage assemble, elapsed time: 0:00:00.000489
2024-05-29 11:25:39,548 [INFO] USER:Berkay_Buharali meta_processor.py:483:create_meta LOG: Bundle path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/bundles/task01_240529.112539
2024-05-29 11:25:39,550 [INFO] USER:Berkay_Buharali helper.py:299:write_content_to_file LOG: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/.syndicate-config-dev/bundles/task01_240529.112539/build_meta.json file was created.
2024-05-29 11:25:39,550 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage package_meta, elapsed time: 0:00:00.001761
2024-05-29 11:25:39,675 [INFO] USER:Berkay_Buharali bundle_processor.py:185:upload_bundle_to_s3 LOG: Bundle was validated successfully
2024-05-29 11:25:39,775 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage upload, elapsed time: 0:00:00.175764
2024-05-29 11:25:39,792 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage build, elapsed time: 0:00:00.478797
2024-05-29 11:25:47,235 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:25:47,490 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:25:47,490 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:25:47,608 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:25:47,608 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: task01
2024-05-29 11:25:47,709 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:25:47,709 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:25:47,813 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:25:47,813 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: task01_240529.112539
2024-05-29 11:25:47,902 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:25:47,902 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:25:48,012 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:25:48,122 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:25:48,122 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:25:48,228 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:25:48,510 [INFO] USER:Berkay_Buharali deployment_processor.py:312:create_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved.
2024-05-29 11:25:48,511 [INFO] USER:Berkay_Buharali deployment_processor.py:345:create_deployment_resources LOG: Going to deploy AWS resources
2024-05-29 11:25:49,595 [INFO] USER:Berkay_Buharali deployment_processor.py:85:_process_resources LOG: Processing iam_policy resources
2024-05-29 11:25:50,099 [WARNING] USER:Berkay_Buharali iam_resource.py:114:_create_policy_from_meta LOG: IAM policy cmtr-5203d48b-lambda-basic-execution exists.
2024-05-29 11:25:50,255 [INFO] USER:Berkay_Buharali deployment_processor.py:97:_process_resources LOG: Processing iam_role resources
2024-05-29 11:25:50,405 [WARNING] USER:Berkay_Buharali iam_resource.py:138:_create_role_from_meta LOG: IAM role cmtr-5203d48b-task01-role exists.
2024-05-29 11:25:50,407 [INFO] USER:Berkay_Buharali deployment_processor.py:348:create_deployment_resources LOG: AWS resources were deployed successfully
2024-05-29 11:25:50,407 [INFO] USER:Berkay_Buharali deployment_processor.py:351:create_deployment_resources LOG: Going to apply dynamic changes
2024-05-29 11:25:50,408 [INFO] USER:Berkay_Buharali deployment_processor.py:353:create_deployment_resources LOG: Dynamic changes were applied successfully
2024-05-29 11:25:50,409 [INFO] USER:Berkay_Buharali deployment_processor.py:355:create_deployment_resources LOG: Going to apply common tags
2024-05-29 11:25:50,417 [INFO] USER:Berkay_Buharali group_tagging_api_resource.py:62:apply_tags LOG: No tags are specified in config. Skipping...
2024-05-29 11:25:50,417 [INFO] USER:Berkay_Buharali deployment_processor.py:358:create_deployment_resources LOG: Going to create deploy output
2024-05-29 11:25:50,521 [INFO] USER:Berkay_Buharali bundle_processor.py:63:create_deploy_output LOG: Output file with name task01_240529.112539/outputs/task01.json has been created
2024-05-29 11:25:50,521 [INFO] USER:Berkay_Buharali deployment_processor.py:364:create_deployment_resources LOG: Deploy output for task01 was created.
2024-05-29 11:25:50,521 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage deploy, elapsed time: 0:00:02.151692
2024-05-29 11:25:50,721 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:25:50,722 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:25:50,848 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:28:54,707 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:28:55,036 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:28:55,036 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:28:55,158 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:28:55,158 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: task01
2024-05-29 11:28:55,278 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:28:55,278 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:28:55,389 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:28:55,389 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: task01_240529.112539
2024-05-29 11:28:55,490 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:28:55,490 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:28:55,598 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:28:55,714 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:28:55,714 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:28:55,851 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:28:55,949 [INFO] USER:Berkay_Buharali deployment_processor.py:446:remove_deployment_resources LOG: Output file was loaded successfully
2024-05-29 11:28:55,949 [INFO] USER:Berkay_Buharali deployment_processor.py:450:remove_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved.
2024-05-29 11:28:55,949 [INFO] USER:Berkay_Buharali deployment_processor.py:481:remove_deployment_resources LOG: Going to clean AWS resources
2024-05-29 11:28:55,949 [INFO] USER:Berkay_Buharali deployment_processor.py:176:clean_resources LOG: Removing iam_role resources ...
2024-05-29 11:28:58,497 [INFO] USER:Berkay_Buharali iam_resource.py:82:_remove_role LOG: IAM role cmtr-5203d48b-task01-role was removed.
2024-05-29 11:28:58,498 [INFO] USER:Berkay_Buharali deployment_processor.py:183:clean_resources LOG: Removing iam_policy resources ...
2024-05-29 11:28:58,867 [INFO] USER:Berkay_Buharali iam_resource.py:46:_remove_policy LOG: IAM policy cmtr-5203d48b-lambda-basic-execution was removed.
2024-05-29 11:28:58,901 [WARNING] USER:Berkay_Buharali bundle_processor.py:93:remove_failed_deploy_output LOG: Failed output file for deploy task01 does not exist.
2024-05-29 11:28:58,901 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage clean, elapsed time: 0:00:03.049965
2024-05-29 11:28:58,976 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:28:58,977 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:28:59,240 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:28:59,240 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:28:59,357 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:29:08,764 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:29:08,944 [INFO] USER:Berkay_Buharali bundle_processor.py:207:create_bundles_bucket LOG: Bundles bucket syndicate-education-platform-custom-sandbox-artifacts-sbox01 already exists
2024-05-29 11:29:08,944 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage create_deploy_target_bucket, elapsed time: 0:00:00.180232
2024-05-29 11:29:16,864 [DEBUG] USER:Berkay_Buharali helper.py:758:set_debug_log_level LOG: The logs level was set to DEBUG
2024-05-29 11:29:16,934 [DEBUG] USER:Berkay_Buharali s3_connection.py:45:__init__ LOG: Opened new S3 connection.
2024-05-29 11:29:16,934 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:29:17,234 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage test, elapsed time: 0:00:00.000126
2024-05-29 11:29:17,263 [INFO] USER:Berkay_Buharali project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/jsrc/main/java/com/task01.
2024-05-29 11:29:17,263 [INFO] USER:Berkay_Buharali project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/src/lambdas.
2024-05-29 11:29:17,263 [INFO] USER:Berkay_Buharali project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/app/lambdas.
2024-05-29 11:29:17,263 [INFO] USER:Berkay_Buharali project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/swagger_src.
2024-05-29 11:29:17,263 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage assemble, elapsed time: 0:00:00.000525
2024-05-29 11:29:17,280 [INFO] USER:Berkay_Buharali meta_processor.py:483:create_meta LOG: Bundle path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/bundles/task01_240529.112916
2024-05-29 11:29:17,281 [DEBUG] USER:Berkay_Buharali meta_processor.py:397:_look_for_configs LOG: Processing file: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/BbAwsServerlessTask01/deployment_resources.json
2024-05-29 11:29:17,281 [DEBUG] USER:Berkay_Buharali meta_processor.py:401:_look_for_configs LOG: Found resource lambda-basic-execution
2024-05-29 11:29:17,281 [DEBUG] USER:Berkay_Buharali meta_processor.py:401:_look_for_configs LOG: Found resource task01-role
2024-05-29 11:29:17,282 [INFO] USER:Berkay_Buharali helper.py:299:write_content_to_file LOG: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/.syndicate-config-dev/bundles/task01_240529.112916/build_meta.json file was created.
2024-05-29 11:29:17,282 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage package_meta, elapsed time: 0:00:00.001895
2024-05-29 11:29:17,407 [INFO] USER:Berkay_Buharali bundle_processor.py:185:upload_bundle_to_s3 LOG: Bundle was validated successfully
2024-05-29 11:29:17,407 [DEBUG] USER:Berkay_Buharali bundle_processor.py:195:upload_bundle_to_s3 LOG: Going to upload file: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/.syndicate-config-dev/bundles/task01_240529.112916/build_meta.json
2024-05-29 11:29:17,487 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage upload, elapsed time: 0:00:00.156019
2024-05-29 11:29:17,504 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage build, elapsed time: 0:00:00.463176
2024-05-29 11:30:29,358 [DEBUG] USER:Berkay_Buharali helper.py:758:set_debug_log_level LOG: The logs level was set to DEBUG
2024-05-29 11:30:29,429 [DEBUG] USER:Berkay_Buharali s3_connection.py:45:__init__ LOG: Opened new S3 connection.
2024-05-29 11:30:29,429 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:30:29,772 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage test, elapsed time: 0:00:00.000173
2024-05-29 11:30:29,802 [INFO] USER:Berkay_Buharali project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/jsrc/main/java/com/task01.
2024-05-29 11:30:29,802 [INFO] USER:Berkay_Buharali project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/src/lambdas.
2024-05-29 11:30:29,802 [INFO] USER:Berkay_Buharali project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/app/lambdas.
2024-05-29 11:30:29,802 [INFO] USER:Berkay_Buharali project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/swagger_src.
2024-05-29 11:30:29,802 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage assemble, elapsed time: 0:00:00.000443
2024-05-29 11:30:29,821 [INFO] USER:Berkay_Buharali meta_processor.py:483:create_meta LOG: Bundle path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/bundles/task01_240529.113029
2024-05-29 11:30:29,821 [DEBUG] USER:Berkay_Buharali meta_processor.py:397:_look_for_configs LOG: Processing file: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/BbAwsServerlessTask01/deployment_resources.json
2024-05-29 11:30:29,822 [DEBUG] USER:Berkay_Buharali meta_processor.py:401:_look_for_configs LOG: Found resource lambda-basic-execution
2024-05-29 11:30:29,822 [DEBUG] USER:Berkay_Buharali meta_processor.py:401:_look_for_configs LOG: Found resource task01-role
2024-05-29 11:30:29,822 [DEBUG] USER:Berkay_Buharali meta_processor.py:397:_look_for_configs LOG: Processing file: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/BbAwsServerlessTask01/target/deployment_resources.json
2024-05-29 11:30:29,822 [DEBUG] USER:Berkay_Buharali meta_processor.py:401:_look_for_configs LOG: Found resource task01
2024-05-29 11:30:29,823 [INFO] USER:Berkay_Buharali helper.py:299:write_content_to_file LOG: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/.syndicate-config-dev/bundles/task01_240529.113029/build_meta.json file was created.
2024-05-29 11:30:29,823 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage package_meta, elapsed time: 0:00:00.002123
2024-05-29 11:30:29,950 [INFO] USER:Berkay_Buharali bundle_processor.py:185:upload_bundle_to_s3 LOG: Bundle was validated successfully
2024-05-29 11:30:29,951 [DEBUG] USER:Berkay_Buharali bundle_processor.py:195:upload_bundle_to_s3 LOG: Going to upload file: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/.syndicate-config-dev/bundles/task01_240529.113029/build_meta.json
2024-05-29 11:30:30,034 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage upload, elapsed time: 0:00:00.159939
2024-05-29 11:30:30,050 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage build, elapsed time: 0:00:00.489760
2024-05-29 11:30:52,486 [DEBUG] USER:Berkay_Buharali helper.py:758:set_debug_log_level LOG: The logs level was set to DEBUG
2024-05-29 11:30:52,486 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:30:52,549 [DEBUG] USER:Berkay_Buharali s3_connection.py:45:__init__ LOG: Opened new S3 connection.
2024-05-29 11:30:52,695 [DEBUG] USER:Berkay_Buharali sync_processor.py:38:sync_project_state LOG: Syncing with remote .syndicate file.
2024-05-29 11:30:52,761 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:30:52,761 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:30:52,761 [DEBUG] USER:Berkay_Buharali sync_processor.py:41:sync_project_state LOG: Actualizing the project state...
2024-05-29 11:30:52,781 [DEBUG] USER:Berkay_Buharali sync_processor.py:46:sync_project_state LOG: Saving a local .syndicate file.
2024-05-29 11:30:52,796 [DEBUG] USER:Berkay_Buharali sync_processor.py:49:sync_project_state LOG: Synced the .syndicate file. Pushing...
2024-05-29 11:30:52,902 [DEBUG] USER:Berkay_Buharali sync_processor.py:51:sync_project_state LOG: Push successful
2024-05-29 11:30:52,902 [DEBUG] USER:Berkay_Buharali sync_processor.py:52:sync_project_state LOG: Remote .syndicate file pulled
2024-05-29 11:30:52,902 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:30:52,903 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: task01
2024-05-29 11:30:53,006 [DEBUG] USER:Berkay_Buharali sync_processor.py:38:sync_project_state LOG: Syncing with remote .syndicate file.
2024-05-29 11:30:53,081 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:30:53,081 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:30:53,081 [DEBUG] USER:Berkay_Buharali sync_processor.py:41:sync_project_state LOG: Actualizing the project state...
2024-05-29 11:30:53,098 [DEBUG] USER:Berkay_Buharali sync_processor.py:46:sync_project_state LOG: Saving a local .syndicate file.
2024-05-29 11:30:53,112 [DEBUG] USER:Berkay_Buharali sync_processor.py:49:sync_project_state LOG: Synced the .syndicate file. Pushing...
2024-05-29 11:30:53,199 [DEBUG] USER:Berkay_Buharali sync_processor.py:51:sync_project_state LOG: Push successful
2024-05-29 11:30:53,199 [DEBUG] USER:Berkay_Buharali sync_processor.py:52:sync_project_state LOG: Remote .syndicate file pulled
2024-05-29 11:30:53,199 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:30:53,199 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: task01_240529.113029
2024-05-29 11:30:53,232 [DEBUG] USER:Berkay_Buharali sync_processor.py:38:sync_project_state LOG: Syncing with remote .syndicate file.
2024-05-29 11:30:53,298 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:30:53,298 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:30:53,298 [DEBUG] USER:Berkay_Buharali sync_processor.py:41:sync_project_state LOG: Actualizing the project state...
2024-05-29 11:30:53,314 [DEBUG] USER:Berkay_Buharali sync_processor.py:46:sync_project_state LOG: Saving a local .syndicate file.
2024-05-29 11:30:53,327 [DEBUG] USER:Berkay_Buharali sync_processor.py:49:sync_project_state LOG: Synced the .syndicate file. Pushing...
2024-05-29 11:30:53,426 [DEBUG] USER:Berkay_Buharali sync_processor.py:51:sync_project_state LOG: Push successful
2024-05-29 11:30:53,426 [DEBUG] USER:Berkay_Buharali sync_processor.py:52:sync_project_state LOG: Remote .syndicate file pulled
2024-05-29 11:30:53,426 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:30:53,474 [DEBUG] USER:Berkay_Buharali sync_processor.py:38:sync_project_state LOG: Syncing with remote .syndicate file.
2024-05-29 11:30:53,540 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:30:53,540 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:30:53,540 [DEBUG] USER:Berkay_Buharali sync_processor.py:41:sync_project_state LOG: Actualizing the project state...
2024-05-29 11:30:53,555 [DEBUG] USER:Berkay_Buharali sync_processor.py:46:sync_project_state LOG: Saving a local .syndicate file.
2024-05-29 11:30:53,568 [DEBUG] USER:Berkay_Buharali sync_processor.py:49:sync_project_state LOG: Synced the .syndicate file. Pushing...
2024-05-29 11:30:53,649 [DEBUG] USER:Berkay_Buharali sync_processor.py:51:sync_project_state LOG: Push successful
2024-05-29 11:30:53,649 [DEBUG] USER:Berkay_Buharali sync_processor.py:52:sync_project_state LOG: Remote .syndicate file pulled
2024-05-29 11:30:53,649 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:30:53,828 [DEBUG] USER:Berkay_Buharali deployment_processor.py:299:create_deployment_resources LOG: Latest deploy output:
 {}
2024-05-29 11:30:53,867 [DEBUG] USER:Berkay_Buharali deployment_processor.py:303:create_deployment_resources LOG: build_meta.json file was loaded successfully
2024-05-29 11:30:53,867 [DEBUG] USER:Berkay_Buharali meta_processor.py:495:resolve_meta LOG: Resolved meta was created
2024-05-29 11:30:53,868 [DEBUG] USER:Berkay_Buharali meta_processor.py:496:resolve_meta LOG: {
    "lambda-basic-execution": {
        "policy_content": {
            "Statement": [
                {
                    "Action": [
                        "logs:CreateLogGroup",
                        "logs:CreateLogStream",
                        "logs:PutLogEvents",
                        "dynamodb:GetItem",
                        "dynamodb:Query",
                        "dynamodb:PutItem",
                        "dynamodb:Batch*",
                        "dynamodb:DeleteItem",
                        "ssm:PutParameter",
                        "ssm:GetParameter",
                        "kms:Decrypt"
                    ],
                    "Effect": "Allow",
                    "Resource": "*"
                }
            ],
            "Version": "2012-10-17"
        },
        "resource_type": "iam_policy"
    },
    "task01-role": {
        "predefined_policies": [],
        "principal_service": "lambda",
        "custom_policies": [
            "lambda-basic-execution"
        ],
        "resource_type": "iam_role"
    },
    "task01": {
        "name": "task01",
        "lambda_path": "/Users/Berkay_Buharali/Learn/AWS_Serverless/task01/BbAwsServerlessTask01",
        "version": "1.0.0",
        "func_name": "com.BbAwsServerlessTask01.Task01",
        "deployment_package": "BbAwsServerlessTask01-1.0.0.jar",
        "resource_type": "lambda",
        "runtime": "java11",
        "architectures": [
            "x86_64"
        ],
        "iam_role_name": "task01-role",
        "memory": 1024,
        "timeout": 300,
        "subnet_ids": [],
        "security_group_ids": [],
        "dependencies": [],
        "event_sources": [],
        "env_variables": {},
        "publish_version": true,
        "alias": "dev",
        "logs_expiration": "30",
        "snap_start": "None"
    }
}
2024-05-29 11:30:53,868 [DEBUG] USER:Berkay_Buharali meta_processor.py:498:resolve_meta LOG: Permissions boundary were resolved
2024-05-29 11:30:53,868 [DEBUG] USER:Berkay_Buharali meta_processor.py:517:resolve_meta LOG: Going to resolve names in meta
2024-05-29 11:30:53,868 [DEBUG] USER:Berkay_Buharali meta_processor.py:518:resolve_meta LOG: Resolved names mapping: {'lambda-basic-execution': 'cmtr-5203d48b-lambda-basic-execution', 'task01-role': 'cmtr-5203d48b-task01-role', 'task01': 'cmtr-5203d48b-task01'}
2024-05-29 11:30:53,868 [DEBUG] USER:Berkay_Buharali deployment_processor.py:306:create_deployment_resources LOG: Names were resolved
2024-05-29 11:30:53,868 [DEBUG] USER:Berkay_Buharali deployment_processor.py:308:create_deployment_resources LOG: Artifacts s3 paths were resolved
2024-05-29 11:30:53,868 [INFO] USER:Berkay_Buharali deployment_processor.py:312:create_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved.
2024-05-29 11:30:53,868 [DEBUG] USER:Berkay_Buharali deployment_processor.py:331:create_deployment_resources LOG: {
    "cmtr-5203d48b-lambda-basic-execution": {
        "policy_content": {
            "Statement": [
                {
                    "Action": [
                        "logs:CreateLogGroup",
                        "logs:CreateLogStream",
                        "logs:PutLogEvents",
                        "dynamodb:GetItem",
                        "dynamodb:Query",
                        "dynamodb:PutItem",
                        "dynamodb:Batch*",
                        "dynamodb:DeleteItem",
                        "ssm:PutParameter",
                        "ssm:GetParameter",
                        "kms:Decrypt"
                    ],
                    "Effect": "Allow",
                    "Resource": "*"
                }
            ],
            "Version": "2012-10-17"
        },
        "resource_type": "iam_policy"
    },
    "cmtr-5203d48b-task01-role": {
        "predefined_policies": [],
        "principal_service": "lambda",
        "custom_policies": [
            "cmtr-5203d48b-lambda-basic-execution"
        ],
        "resource_type": "iam_role",
        "permissions_boundary": "arn:aws:iam::196241772369:policy/eo_role_boundary"
    },
    "cmtr-5203d48b-task01": {
        "name": "cmtr-5203d48b-task01",
        "lambda_path": "/Users/Berkay_Buharali/Learn/AWS_Serverless/task01/BbAwsServerlessTask01",
        "version": "1.0.0",
        "func_name": "com.BbAwsServerlessTask01.Task01",
        "deployment_package": "BbAwsServerlessTask01-1.0.0.jar",
        "resource_type": "lambda",
        "runtime": "java11",
        "architectures": [
            "x86_64"
        ],
        "iam_role_name": "cmtr-5203d48b-task01-role",
        "memory": 1024,
        "timeout": 300,
        "subnet_ids": [],
        "security_group_ids": [],
        "dependencies": [],
        "event_sources": [],
        "env_variables": {},
        "publish_version": true,
        "alias": "dev",
        "logs_expiration": "30",
        "snap_start": "None",
        "prefix": "cmtr-5203d48b-",
        "suffix": "",
        "s3_path": "task01_240529.113029/BbAwsServerlessTask01-1.0.0.jar"
    }
}
2024-05-29 11:30:53,869 [DEBUG] USER:Berkay_Buharali deployment_processor.py:333:create_deployment_resources LOG: Going to create: {
    "cmtr-5203d48b-lambda-basic-execution": {
        "policy_content": {
            "Statement": [
                {
                    "Action": [
                        "logs:CreateLogGroup",
                        "logs:CreateLogStream",
                        "logs:PutLogEvents",
                        "dynamodb:GetItem",
                        "dynamodb:Query",
                        "dynamodb:PutItem",
                        "dynamodb:Batch*",
                        "dynamodb:DeleteItem",
                        "ssm:PutParameter",
                        "ssm:GetParameter",
                        "kms:Decrypt"
                    ],
                    "Effect": "Allow",
                    "Resource": "*"
                }
            ],
            "Version": "2012-10-17"
        },
        "resource_type": "iam_policy"
    },
    "cmtr-5203d48b-task01-role": {
        "predefined_policies": [],
        "principal_service": "lambda",
        "custom_policies": [
            "cmtr-5203d48b-lambda-basic-execution"
        ],
        "resource_type": "iam_role",
        "permissions_boundary": "arn:aws:iam::196241772369:policy/eo_role_boundary"
    },
    "cmtr-5203d48b-task01": {
        "name": "cmtr-5203d48b-task01",
        "lambda_path": "/Users/Berkay_Buharali/Learn/AWS_Serverless/task01/BbAwsServerlessTask01",
        "version": "1.0.0",
        "func_name": "com.BbAwsServerlessTask01.Task01",
        "deployment_package": "BbAwsServerlessTask01-1.0.0.jar",
        "resource_type": "lambda",
        "runtime": "java11",
        "architectures": [
            "x86_64"
        ],
        "iam_role_name": "cmtr-5203d48b-task01-role",
        "memory": 1024,
        "timeout": 300,
        "subnet_ids": [],
        "security_group_ids": [],
        "dependencies": [],
        "event_sources": [],
        "env_variables": {},
        "publish_version": true,
        "alias": "dev",
        "logs_expiration": "30",
        "snap_start": "None",
        "prefix": "cmtr-5203d48b-",
        "suffix": "",
        "s3_path": "task01_240529.113029/BbAwsServerlessTask01-1.0.0.jar"
    }
}
2024-05-29 11:30:53,869 [INFO] USER:Berkay_Buharali deployment_processor.py:345:create_deployment_resources LOG: Going to deploy AWS resources
2024-05-29 11:30:53,943 [DEBUG] USER:Berkay_Buharali iam_connection.py:51:__init__ LOG: Opened new IAM connection.
2024-05-29 11:30:53,987 [DEBUG] USER:Berkay_Buharali lambda_connection.py:59:__init__ LOG: Opened new Lambda connection.
2024-05-29 11:30:53,995 [DEBUG] USER:Berkay_Buharali s3_connection.py:45:__init__ LOG: Opened new S3 connection.
2024-05-29 11:30:54,037 [DEBUG] USER:Berkay_Buharali cloud_watch_connection.py:47:__init__ LOG: Opened new Cloudwatch logs connection.
2024-05-29 11:30:54,083 [DEBUG] USER:Berkay_Buharali dynamo_connection.py:112:__init__ LOG: Opened new DynamoDB connection.
2024-05-29 11:30:54,120 [DEBUG] USER:Berkay_Buharali sqs_connection.py:40:__init__ LOG: Opened new SQS connection.
2024-05-29 11:30:54,152 [DEBUG] USER:Berkay_Buharali kinesis_connection.py:41:__init__ LOG: Opened new Kinesis connection.
2024-05-29 11:30:54,197 [DEBUG] USER:Berkay_Buharali cloud_watch_connection.py:163:__init__ LOG: Opened new Cloudwatch events connection.
2024-05-29 11:30:54,234 [DEBUG] USER:Berkay_Buharali cloud_watch_connection.py:386:__init__ LOG: Opened new Cloudwatch metric connection.
2024-05-29 11:30:54,272 [DEBUG] USER:Berkay_Buharali application_autoscaling_connection.py:36:__init__ LOG: Opened new Application autoscaling connection.
2024-05-29 11:30:54,317 [DEBUG] USER:Berkay_Buharali api_gateway_connection.py:55:__init__ LOG: Opened new API Gateway connection.
2024-05-29 11:30:54,351 [DEBUG] USER:Berkay_Buharali cognito_identity_provider_connection.py:38:__init__ LOG: Opened new Cognito identity connection.
2024-05-29 11:30:54,387 [DEBUG] USER:Berkay_Buharali cognito_identity_connection.py:39:__init__ LOG: Opened new Cognito identity connection.
2024-05-29 11:30:54,394 [DEBUG] USER:Berkay_Buharali cloud_watch_connection.py:386:__init__ LOG: Opened new Cloudwatch metric connection.
2024-05-29 11:30:54,437 [DEBUG] USER:Berkay_Buharali sns_connection.py:36:__init__ LOG: Opened new SNS connection.
2024-05-29 11:30:54,504 [DEBUG] USER:Berkay_Buharali ec2_connection.py:60:__init__ LOG: Opened new EC2 connection.
2024-05-29 11:30:54,550 [DEBUG] USER:Berkay_Buharali elastic_beanstalk_connection.py:35:__init__ LOG: Opened new Elastic beanstalk connection.
2024-05-29 11:30:54,585 [DEBUG] USER:Berkay_Buharali step_functions_connection.py:37:__init__ LOG: Opened new Step Functions connection.
2024-05-29 11:30:54,617 [DEBUG] USER:Berkay_Buharali batch_connection.py:37:__init__ LOG: Opened new Batch connection.
2024-05-29 11:30:54,656 [DEBUG] USER:Berkay_Buharali documentdb_connection.py:39:__init__ LOG: Opened new DocumentDB connection.
2024-05-29 11:30:54,708 [DEBUG] USER:Berkay_Buharali dax_connection.py:34:__init__ LOG: Opened new DAX connection.
2024-05-29 11:30:54,750 [DEBUG] USER:Berkay_Buharali firehose_connection.py:20:__init__ LOG: Opened new Firehose connection.
2024-05-29 11:30:54,806 [DEBUG] USER:Berkay_Buharali eventbridge_scheduler_connection.py:20:__init__ LOG: Opened new EventBridge Scheduler connection.
2024-05-29 11:30:54,806 [INFO] USER:Berkay_Buharali deployment_processor.py:85:_process_resources LOG: Processing iam_policy resources
2024-05-29 11:30:55,492 [INFO] USER:Berkay_Buharali iam_resource.py:118:_create_policy_from_meta LOG: Created IAM policy cmtr-5203d48b-lambda-basic-execution.
2024-05-29 11:30:55,666 [INFO] USER:Berkay_Buharali deployment_processor.py:85:_process_resources LOG: Processing iam_role resources
2024-05-29 11:30:58,966 [INFO] USER:Berkay_Buharali iam_resource.py:178:_create_role_from_meta LOG: Created IAM role cmtr-5203d48b-task01-role.
2024-05-29 11:30:58,967 [INFO] USER:Berkay_Buharali deployment_processor.py:97:_process_resources LOG: Processing lambda resources
2024-05-29 11:30:58,967 [DEBUG] USER:Berkay_Buharali lambda_resource.py:260:_create_lambda_from_meta LOG: Creating lambda cmtr-5203d48b-task01
2024-05-29 11:30:59,123 [ERROR] USER:Berkay_Buharali deployment_processor.py:104:_process_resources LOG: Error occurred while lambda resource creating: Error while creating lambda: cmtr-5203d48b-task01;Deployment package 5203d48b/task01/task01_240529.113029/BbAwsServerlessTask01-1.0.0.jar does not exist in syndicate-education-platform-custom-sandbox-artifacts-sbox01 bucket
Traceback (most recent call last):
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/build/deployment_processor.py", line 99, in _process_resources
    response = func(args)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/resources/lambda_resource.py", line 161, in create_lambda
    return self.create_pool(self._create_lambda_from_meta, args)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/resources/base_resource.py", line 41, in create_pool
    result = future.result()
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/helper.py", line 66, in wrapper
    return handler_func(**parameters)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/connection/helper.py", line 91, in wrapper
    return handler_func(*args, **kwargs)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/resources/lambda_resource.py", line 271, in _create_lambda_from_meta
    raise AssertionError(f'Error while creating lambda: {name};'
AssertionError: Error while creating lambda: cmtr-5203d48b-task01;Deployment package 5203d48b/task01/task01_240529.113029/BbAwsServerlessTask01-1.0.0.jar does not exist in syndicate-education-platform-custom-sandbox-artifacts-sbox01 bucket
2024-05-29 11:30:59,245 [WARNING] USER:Berkay_Buharali deployment_processor.py:142:update_failed_output LOG: Unable to describe lambda resource with name cmtr-5203d48b-task01. Exception: 'NoneType' object is not subscriptable
2024-05-29 11:30:59,245 [INFO] USER:Berkay_Buharali deployment_processor.py:358:create_deployment_resources LOG: Going to create deploy output
2024-05-29 11:30:59,358 [INFO] USER:Berkay_Buharali bundle_processor.py:63:create_deploy_output LOG: Output file with name task01_240529.113029/outputs/task01_failed.json has been created
2024-05-29 11:30:59,358 [INFO] USER:Berkay_Buharali deployment_processor.py:364:create_deployment_resources LOG: Deploy output for task01 was created.
2024-05-29 11:30:59,358 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage deploy, elapsed time: 0:00:05.530439
2024-05-29 11:30:59,445 [DEBUG] USER:Berkay_Buharali sync_processor.py:38:sync_project_state LOG: Syncing with remote .syndicate file.
2024-05-29 11:30:59,513 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:30:59,513 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:30:59,513 [DEBUG] USER:Berkay_Buharali sync_processor.py:41:sync_project_state LOG: Actualizing the project state...
2024-05-29 11:30:59,529 [DEBUG] USER:Berkay_Buharali sync_processor.py:46:sync_project_state LOG: Saving a local .syndicate file.
2024-05-29 11:30:59,543 [DEBUG] USER:Berkay_Buharali sync_processor.py:49:sync_project_state LOG: Synced the .syndicate file. Pushing...
2024-05-29 11:30:59,622 [DEBUG] USER:Berkay_Buharali sync_processor.py:51:sync_project_state LOG: Push successful
2024-05-29 11:30:59,622 [DEBUG] USER:Berkay_Buharali sync_processor.py:52:sync_project_state LOG: Remote .syndicate file pulled
2024-05-29 11:30:59,622 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:33:59,577 [DEBUG] USER:Berkay_Buharali helper.py:758:set_debug_log_level LOG: The logs level was set to DEBUG
2024-05-29 11:33:59,640 [DEBUG] USER:Berkay_Buharali s3_connection.py:45:__init__ LOG: Opened new S3 connection.
2024-05-29 11:33:59,640 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:33:59,973 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage test, elapsed time: 0:00:00.000148
2024-05-29 11:34:00,006 [INFO] USER:Berkay_Buharali project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/jsrc/main/java/com/task01.
2024-05-29 11:34:00,006 [INFO] USER:Berkay_Buharali project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/src/lambdas.
2024-05-29 11:34:00,006 [INFO] USER:Berkay_Buharali project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/app/lambdas.
2024-05-29 11:34:00,006 [INFO] USER:Berkay_Buharali project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/swagger_src.
2024-05-29 11:34:00,006 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage assemble, elapsed time: 0:00:00.000375
2024-05-29 11:34:00,025 [INFO] USER:Berkay_Buharali meta_processor.py:483:create_meta LOG: Bundle path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/bundles/task01_240529.113359
2024-05-29 11:34:00,026 [DEBUG] USER:Berkay_Buharali meta_processor.py:397:_look_for_configs LOG: Processing file: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/BbAwsServerlessTask01/deployment_resources.json
2024-05-29 11:34:00,026 [DEBUG] USER:Berkay_Buharali meta_processor.py:401:_look_for_configs LOG: Found resource lambda-basic-execution
2024-05-29 11:34:00,026 [DEBUG] USER:Berkay_Buharali meta_processor.py:401:_look_for_configs LOG: Found resource task01-role
2024-05-29 11:34:00,026 [DEBUG] USER:Berkay_Buharali meta_processor.py:397:_look_for_configs LOG: Processing file: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/BbAwsServerlessTask01/target/deployment_resources.json
2024-05-29 11:34:00,027 [DEBUG] USER:Berkay_Buharali meta_processor.py:401:_look_for_configs LOG: Found resource task01
2024-05-29 11:34:00,029 [INFO] USER:Berkay_Buharali helper.py:299:write_content_to_file LOG: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/.syndicate-config-dev/bundles/task01_240529.113359/build_meta.json file was created.
2024-05-29 11:34:00,029 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage package_meta, elapsed time: 0:00:00.003639
2024-05-29 11:34:00,162 [INFO] USER:Berkay_Buharali bundle_processor.py:185:upload_bundle_to_s3 LOG: Bundle was validated successfully
2024-05-29 11:34:00,162 [DEBUG] USER:Berkay_Buharali bundle_processor.py:195:upload_bundle_to_s3 LOG: Going to upload file: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/.syndicate-config-dev/bundles/task01_240529.113359/build_meta.json
2024-05-29 11:34:00,236 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage upload, elapsed time: 0:00:00.154760
2024-05-29 11:34:00,253 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage build, elapsed time: 0:00:00.498017
2024-05-29 11:34:16,943 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:34:17,229 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:34:17,230 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:34:17,367 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:34:17,367 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: task01_240529.113359
2024-05-29 11:34:17,482 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:34:17,482 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:34:17,607 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:34:17,607 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: task01
2024-05-29 11:34:17,713 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:34:17,713 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:34:17,820 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:34:17,941 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:34:17,941 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:34:18,064 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:34:18,923 [WARNING] USER:Berkay_Buharali deployment_processor.py:381:update_deployment_resources LOG: Please pay attention that only the following resources types are supported for update: ['iam_role', 'iam_policy', 'lambda', 'lambda_layer', 'api_gateway_oas_v3', 'batch_jobdef', 'batch_compenv', 'eventbridge_schedule', 'dynamodb_table', 'swagger_ui', 'ec2_launch_template']
2024-05-29 11:34:18,924 [INFO] USER:Berkay_Buharali deployment_processor.py:387:update_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved.
2024-05-29 11:34:18,924 [INFO] USER:Berkay_Buharali deployment_processor.py:85:_process_resources LOG: Processing iam_policy resources
2024-05-29 11:34:20,398 [WARNING] USER:Berkay_Buharali iam_connection.py:588:update_custom_policy_content LOG: No need to update policy 'cmtr-5203d48b-lambda-basic-execution': the new and the old contents are identical.
2024-05-29 11:34:20,398 [INFO] USER:Berkay_Buharali iam_resource.py:321:_update_policy_from_meta LOG: Updated IAM policy cmtr-5203d48b-lambda-basic-execution
2024-05-29 11:34:20,553 [INFO] USER:Berkay_Buharali deployment_processor.py:85:_process_resources LOG: Processing iam_role resources
2024-05-29 11:34:20,553 [INFO] USER:Berkay_Buharali iam_resource.py:237:_update_role_from_meta LOG: Updating iam role: cmtr-5203d48b-task01-role
2024-05-29 11:34:20,821 [ERROR] USER:Berkay_Buharali helper.py:105:wrapper LOG: Error occurred: An error occurred (AccessDenied) when calling the UpdateAssumeRolePolicy operation: User: arn:aws:sts::196241772369:assumed-role/cmtr_syndicate_student_programmatic_access/5203d48b is not authorized to perform: iam:UpdateAssumeRolePolicy on resource: role cmtr-5203d48b-task01-role because no identity-based policy allows the iam:UpdateAssumeRolePolicy action
2024-05-29 11:34:20,825 [ERROR] USER:Berkay_Buharali helper.py:106:wrapper LOG: Traceback:
 Traceback (most recent call last):
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/connection/helper.py", line 91, in wrapper
    return handler_func(*args, **kwargs)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/connection/iam_connection.py", line 517, in update_custom_role
    raise e
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/connection/iam_connection.py", line 509, in update_custom_role
    role = self.client.update_assume_role_policy(
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the UpdateAssumeRolePolicy operation: User: arn:aws:sts::196241772369:assumed-role/cmtr_syndicate_student_programmatic_access/5203d48b is not authorized to perform: iam:UpdateAssumeRolePolicy on resource: role cmtr-5203d48b-task01-role because no identity-based policy allows the iam:UpdateAssumeRolePolicy action

2024-05-29 11:34:20,825 [ERROR] USER:Berkay_Buharali deployment_processor.py:104:_process_resources LOG: Error occurred while iam_role resource creating: An error occurred (AccessDenied) when calling the UpdateAssumeRolePolicy operation: User: arn:aws:sts::196241772369:assumed-role/cmtr_syndicate_student_programmatic_access/5203d48b is not authorized to perform: iam:UpdateAssumeRolePolicy on resource: role cmtr-5203d48b-task01-role because no identity-based policy allows the iam:UpdateAssumeRolePolicy action
Traceback (most recent call last):
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/build/deployment_processor.py", line 87, in _process_resources
    response = func(args)  # todo exception may be raised here
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/resources/iam_resource.py", line 230, in update_iam_role
    return self.create_pool(self._update_role_from_meta, args)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/resources/base_resource.py", line 41, in create_pool
    result = future.result()
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/helper.py", line 66, in wrapper
    return handler_func(**parameters)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/resources/iam_resource.py", line 254, in _update_role_from_meta
    response = self.iam_conn.update_custom_role(
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/connection/helper.py", line 107, in wrapper
    raise e
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/connection/helper.py", line 91, in wrapper
    return handler_func(*args, **kwargs)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/connection/iam_connection.py", line 517, in update_custom_role
    raise e
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/connection/iam_connection.py", line 509, in update_custom_role
    role = self.client.update_assume_role_policy(
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the UpdateAssumeRolePolicy operation: User: arn:aws:sts::196241772369:assumed-role/cmtr_syndicate_student_programmatic_access/5203d48b is not authorized to perform: iam:UpdateAssumeRolePolicy on resource: role cmtr-5203d48b-task01-role because no identity-based policy allows the iam:UpdateAssumeRolePolicy action
2024-05-29 11:34:21,412 [INFO] USER:Berkay_Buharali bundle_processor.py:63:create_deploy_output LOG: Output file with name task01_240529.113359/outputs/task01_failed.json has been created
2024-05-29 11:34:21,413 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage update, elapsed time: 0:00:03.203719
2024-05-29 11:34:21,582 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:34:21,582 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:34:21,696 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:34:30,640 [DEBUG] USER:Berkay_Buharali helper.py:758:set_debug_log_level LOG: The logs level was set to DEBUG
2024-05-29 11:34:30,640 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:34:30,671 [DEBUG] USER:Berkay_Buharali s3_connection.py:45:__init__ LOG: Opened new S3 connection.
2024-05-29 11:34:30,811 [DEBUG] USER:Berkay_Buharali sync_processor.py:38:sync_project_state LOG: Syncing with remote .syndicate file.
2024-05-29 11:34:30,889 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:34:30,889 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:34:30,889 [DEBUG] USER:Berkay_Buharali sync_processor.py:41:sync_project_state LOG: Actualizing the project state...
2024-05-29 11:34:30,910 [DEBUG] USER:Berkay_Buharali sync_processor.py:46:sync_project_state LOG: Saving a local .syndicate file.
2024-05-29 11:34:30,925 [DEBUG] USER:Berkay_Buharali sync_processor.py:49:sync_project_state LOG: Synced the .syndicate file. Pushing...
2024-05-29 11:34:31,034 [DEBUG] USER:Berkay_Buharali sync_processor.py:51:sync_project_state LOG: Push successful
2024-05-29 11:34:31,034 [DEBUG] USER:Berkay_Buharali sync_processor.py:52:sync_project_state LOG: Remote .syndicate file pulled
2024-05-29 11:34:31,035 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:34:31,035 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: task01
2024-05-29 11:34:31,073 [DEBUG] USER:Berkay_Buharali sync_processor.py:38:sync_project_state LOG: Syncing with remote .syndicate file.
2024-05-29 11:34:31,148 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:34:31,148 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:34:31,148 [DEBUG] USER:Berkay_Buharali sync_processor.py:41:sync_project_state LOG: Actualizing the project state...
2024-05-29 11:34:31,165 [DEBUG] USER:Berkay_Buharali sync_processor.py:46:sync_project_state LOG: Saving a local .syndicate file.
2024-05-29 11:34:31,180 [DEBUG] USER:Berkay_Buharali sync_processor.py:49:sync_project_state LOG: Synced the .syndicate file. Pushing...
2024-05-29 11:34:31,291 [DEBUG] USER:Berkay_Buharali sync_processor.py:51:sync_project_state LOG: Push successful
2024-05-29 11:34:31,292 [DEBUG] USER:Berkay_Buharali sync_processor.py:52:sync_project_state LOG: Remote .syndicate file pulled
2024-05-29 11:34:31,292 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:34:31,292 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: task01_240529.113359
2024-05-29 11:34:31,325 [DEBUG] USER:Berkay_Buharali sync_processor.py:38:sync_project_state LOG: Syncing with remote .syndicate file.
2024-05-29 11:34:31,397 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:34:31,397 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:34:31,397 [DEBUG] USER:Berkay_Buharali sync_processor.py:41:sync_project_state LOG: Actualizing the project state...
2024-05-29 11:34:31,415 [DEBUG] USER:Berkay_Buharali sync_processor.py:46:sync_project_state LOG: Saving a local .syndicate file.
2024-05-29 11:34:31,430 [DEBUG] USER:Berkay_Buharali sync_processor.py:49:sync_project_state LOG: Synced the .syndicate file. Pushing...
2024-05-29 11:34:31,524 [DEBUG] USER:Berkay_Buharali sync_processor.py:51:sync_project_state LOG: Push successful
2024-05-29 11:34:31,525 [DEBUG] USER:Berkay_Buharali sync_processor.py:52:sync_project_state LOG: Remote .syndicate file pulled
2024-05-29 11:34:31,525 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:34:31,576 [DEBUG] USER:Berkay_Buharali sync_processor.py:38:sync_project_state LOG: Syncing with remote .syndicate file.
2024-05-29 11:34:31,642 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:34:31,643 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:34:31,643 [DEBUG] USER:Berkay_Buharali sync_processor.py:41:sync_project_state LOG: Actualizing the project state...
2024-05-29 11:34:31,660 [DEBUG] USER:Berkay_Buharali sync_processor.py:46:sync_project_state LOG: Saving a local .syndicate file.
2024-05-29 11:34:31,675 [DEBUG] USER:Berkay_Buharali sync_processor.py:49:sync_project_state LOG: Synced the .syndicate file. Pushing...
2024-05-29 11:34:31,764 [DEBUG] USER:Berkay_Buharali sync_processor.py:51:sync_project_state LOG: Push successful
2024-05-29 11:34:31,764 [DEBUG] USER:Berkay_Buharali sync_processor.py:52:sync_project_state LOG: Remote .syndicate file pulled
2024-05-29 11:34:31,764 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:34:31,966 [ERROR] USER:Berkay_Buharali helper.py:84:wrapper LOG: An error occurred. See details in the log file
2024-05-29 11:34:31,966 [ERROR] USER:Berkay_Buharali helper.py:85:wrapper LOG: Error occurred: Deployment output file not found. It might be because the previous deployment failed. If this is the case deployment can be continued by using the command  'syndicate deploy --continue_deploy' or failed deployed resources can be removed with the command 'syndicate clean --rollback'
Traceback (most recent call last):
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/build/bundle_processor.py", line 140, in load_latest_deploy_output
    return load_deploy_output(bundle_name, deploy_name)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/build/bundle_processor.py", line 111, in load_deploy_output
    raise AssertionError('Deploy name {0} does not exist.'
AssertionError: Deploy name task01 does not exist. Cannot find output file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/helper.py", line 82, in wrapper
    return handler_func(*args, **kwargs)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/build/deployment_processor.py", line 298, in create_deployment_resources
    latest_deploy_output = load_latest_deploy_output()
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/build/bundle_processor.py", line 143, in load_latest_deploy_output
    raise AssertionError(
AssertionError: Deployment output file not found. It might be because the previous deployment failed. If this is the case deployment can be continued by using the command  'syndicate deploy --continue_deploy' or failed deployed resources can be removed with the command 'syndicate clean --rollback'
2024-05-29 11:34:32,081 [DEBUG] USER:Berkay_Buharali sync_processor.py:38:sync_project_state LOG: Syncing with remote .syndicate file.
2024-05-29 11:34:32,154 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:34:32,154 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:34:32,154 [DEBUG] USER:Berkay_Buharali sync_processor.py:41:sync_project_state LOG: Actualizing the project state...
2024-05-29 11:34:32,171 [DEBUG] USER:Berkay_Buharali sync_processor.py:46:sync_project_state LOG: Saving a local .syndicate file.
2024-05-29 11:34:32,186 [DEBUG] USER:Berkay_Buharali sync_processor.py:49:sync_project_state LOG: Synced the .syndicate file. Pushing...
2024-05-29 11:34:32,293 [DEBUG] USER:Berkay_Buharali sync_processor.py:51:sync_project_state LOG: Push successful
2024-05-29 11:34:32,293 [DEBUG] USER:Berkay_Buharali sync_processor.py:52:sync_project_state LOG: Remote .syndicate file pulled
2024-05-29 11:34:32,293 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:34:44,882 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:34:45,128 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:34:45,129 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:34:45,255 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:34:45,255 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: task01
2024-05-29 11:34:45,364 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:34:45,365 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:34:45,522 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:34:45,522 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: task01_240529.113029
2024-05-29 11:34:45,631 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:34:45,631 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:34:45,789 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:34:45,914 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:34:45,914 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:34:46,025 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:34:46,092 [INFO] USER:Berkay_Buharali deployment_processor.py:564:remove_failed_deploy_resources LOG: Failed output file was loaded successfully
2024-05-29 11:34:46,092 [INFO] USER:Berkay_Buharali deployment_processor.py:568:remove_failed_deploy_resources LOG: Prefixes and suffixes of any resource names have been resolved.
2024-05-29 11:34:46,093 [INFO] USER:Berkay_Buharali deployment_processor.py:597:remove_failed_deploy_resources LOG: Going to clean AWS resources
2024-05-29 11:34:46,093 [INFO] USER:Berkay_Buharali deployment_processor.py:176:clean_resources LOG: Removing iam_role resources ...
2024-05-29 11:34:47,910 [INFO] USER:Berkay_Buharali iam_resource.py:82:_remove_role LOG: IAM role cmtr-5203d48b-task01-role was removed.
2024-05-29 11:34:47,911 [INFO] USER:Berkay_Buharali deployment_processor.py:183:clean_resources LOG: Removing iam_policy resources ...
2024-05-29 11:34:48,262 [INFO] USER:Berkay_Buharali iam_resource.py:46:_remove_policy LOG: IAM policy cmtr-5203d48b-lambda-basic-execution was removed.
2024-05-29 11:34:48,331 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage clean, elapsed time: 0:00:02.305634
2024-05-29 11:34:48,404 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:34:48,404 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:34:48,638 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:34:48,638 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:34:48,752 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:34:54,088 [DEBUG] USER:Berkay_Buharali helper.py:758:set_debug_log_level LOG: The logs level was set to DEBUG
2024-05-29 11:34:54,088 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:34:54,153 [DEBUG] USER:Berkay_Buharali s3_connection.py:45:__init__ LOG: Opened new S3 connection.
2024-05-29 11:34:54,261 [DEBUG] USER:Berkay_Buharali sync_processor.py:38:sync_project_state LOG: Syncing with remote .syndicate file.
2024-05-29 11:34:54,340 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:34:54,340 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:34:54,340 [DEBUG] USER:Berkay_Buharali sync_processor.py:41:sync_project_state LOG: Actualizing the project state...
2024-05-29 11:34:54,362 [DEBUG] USER:Berkay_Buharali sync_processor.py:46:sync_project_state LOG: Saving a local .syndicate file.
2024-05-29 11:34:54,377 [DEBUG] USER:Berkay_Buharali sync_processor.py:49:sync_project_state LOG: Synced the .syndicate file. Pushing...
2024-05-29 11:34:54,470 [DEBUG] USER:Berkay_Buharali sync_processor.py:51:sync_project_state LOG: Push successful
2024-05-29 11:34:54,470 [DEBUG] USER:Berkay_Buharali sync_processor.py:52:sync_project_state LOG: Remote .syndicate file pulled
2024-05-29 11:34:54,470 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:34:54,470 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: task01
2024-05-29 11:34:54,500 [DEBUG] USER:Berkay_Buharali sync_processor.py:38:sync_project_state LOG: Syncing with remote .syndicate file.
2024-05-29 11:34:54,579 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:34:54,579 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:34:54,579 [DEBUG] USER:Berkay_Buharali sync_processor.py:41:sync_project_state LOG: Actualizing the project state...
2024-05-29 11:34:54,597 [DEBUG] USER:Berkay_Buharali sync_processor.py:46:sync_project_state LOG: Saving a local .syndicate file.
2024-05-29 11:34:54,612 [DEBUG] USER:Berkay_Buharali sync_processor.py:49:sync_project_state LOG: Synced the .syndicate file. Pushing...
2024-05-29 11:34:54,699 [DEBUG] USER:Berkay_Buharali sync_processor.py:51:sync_project_state LOG: Push successful
2024-05-29 11:34:54,699 [DEBUG] USER:Berkay_Buharali sync_processor.py:52:sync_project_state LOG: Remote .syndicate file pulled
2024-05-29 11:34:54,699 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:34:54,699 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: task01_240529.113359
2024-05-29 11:34:54,735 [DEBUG] USER:Berkay_Buharali sync_processor.py:38:sync_project_state LOG: Syncing with remote .syndicate file.
2024-05-29 11:34:54,804 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:34:54,804 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:34:54,805 [DEBUG] USER:Berkay_Buharali sync_processor.py:41:sync_project_state LOG: Actualizing the project state...
2024-05-29 11:34:54,821 [DEBUG] USER:Berkay_Buharali sync_processor.py:46:sync_project_state LOG: Saving a local .syndicate file.
2024-05-29 11:34:54,836 [DEBUG] USER:Berkay_Buharali sync_processor.py:49:sync_project_state LOG: Synced the .syndicate file. Pushing...
2024-05-29 11:34:54,923 [DEBUG] USER:Berkay_Buharali sync_processor.py:51:sync_project_state LOG: Push successful
2024-05-29 11:34:54,923 [DEBUG] USER:Berkay_Buharali sync_processor.py:52:sync_project_state LOG: Remote .syndicate file pulled
2024-05-29 11:34:54,923 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:34:54,969 [DEBUG] USER:Berkay_Buharali sync_processor.py:38:sync_project_state LOG: Syncing with remote .syndicate file.
2024-05-29 11:34:55,039 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:34:55,039 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:34:55,039 [DEBUG] USER:Berkay_Buharali sync_processor.py:41:sync_project_state LOG: Actualizing the project state...
2024-05-29 11:34:55,055 [DEBUG] USER:Berkay_Buharali sync_processor.py:46:sync_project_state LOG: Saving a local .syndicate file.
2024-05-29 11:34:55,069 [DEBUG] USER:Berkay_Buharali sync_processor.py:49:sync_project_state LOG: Synced the .syndicate file. Pushing...
2024-05-29 11:34:55,168 [DEBUG] USER:Berkay_Buharali sync_processor.py:51:sync_project_state LOG: Push successful
2024-05-29 11:34:55,168 [DEBUG] USER:Berkay_Buharali sync_processor.py:52:sync_project_state LOG: Remote .syndicate file pulled
2024-05-29 11:34:55,168 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:34:55,306 [DEBUG] USER:Berkay_Buharali deployment_processor.py:299:create_deployment_resources LOG: Latest deploy output:
 {}
2024-05-29 11:34:55,344 [DEBUG] USER:Berkay_Buharali deployment_processor.py:303:create_deployment_resources LOG: build_meta.json file was loaded successfully
2024-05-29 11:34:55,344 [DEBUG] USER:Berkay_Buharali meta_processor.py:495:resolve_meta LOG: Resolved meta was created
2024-05-29 11:34:55,345 [DEBUG] USER:Berkay_Buharali meta_processor.py:496:resolve_meta LOG: {
    "lambda-basic-execution": {
        "policy_content": {
            "Statement": [
                {
                    "Action": [
                        "logs:CreateLogGroup",
                        "logs:CreateLogStream",
                        "logs:PutLogEvents",
                        "dynamodb:GetItem",
                        "dynamodb:Query",
                        "dynamodb:PutItem",
                        "dynamodb:Batch*",
                        "dynamodb:DeleteItem",
                        "ssm:PutParameter",
                        "ssm:GetParameter",
                        "kms:Decrypt"
                    ],
                    "Effect": "Allow",
                    "Resource": "*"
                }
            ],
            "Version": "2012-10-17"
        },
        "resource_type": "iam_policy"
    },
    "task01-role": {
        "predefined_policies": [],
        "principal_service": "lambda",
        "custom_policies": [
            "lambda-basic-execution"
        ],
        "resource_type": "iam_role"
    },
    "task01": {
        "name": "task01",
        "lambda_path": "/Users/Berkay_Buharali/Learn/AWS_Serverless/task01/BbAwsServerlessTask01",
        "version": "1.0.0",
        "func_name": "com.BbAwsServerlessTask01.Task01",
        "deployment_package": "BbAwsServerlessTask01-1.0.0.jar",
        "resource_type": "lambda",
        "runtime": "java11",
        "architectures": [
            "x86_64"
        ],
        "iam_role_name": "task01-role",
        "memory": 1024,
        "timeout": 300,
        "subnet_ids": [],
        "security_group_ids": [],
        "dependencies": [],
        "event_sources": [],
        "env_variables": {},
        "publish_version": true,
        "alias": "dev",
        "logs_expiration": "30",
        "snap_start": "None"
    }
}
2024-05-29 11:34:55,345 [DEBUG] USER:Berkay_Buharali meta_processor.py:498:resolve_meta LOG: Permissions boundary were resolved
2024-05-29 11:34:55,345 [DEBUG] USER:Berkay_Buharali meta_processor.py:517:resolve_meta LOG: Going to resolve names in meta
2024-05-29 11:34:55,345 [DEBUG] USER:Berkay_Buharali meta_processor.py:518:resolve_meta LOG: Resolved names mapping: {'lambda-basic-execution': 'cmtr-5203d48b-lambda-basic-execution', 'task01-role': 'cmtr-5203d48b-task01-role', 'task01': 'cmtr-5203d48b-task01'}
2024-05-29 11:34:55,345 [DEBUG] USER:Berkay_Buharali deployment_processor.py:306:create_deployment_resources LOG: Names were resolved
2024-05-29 11:34:55,345 [DEBUG] USER:Berkay_Buharali deployment_processor.py:308:create_deployment_resources LOG: Artifacts s3 paths were resolved
2024-05-29 11:34:55,345 [INFO] USER:Berkay_Buharali deployment_processor.py:312:create_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved.
2024-05-29 11:34:55,345 [DEBUG] USER:Berkay_Buharali deployment_processor.py:331:create_deployment_resources LOG: {
    "cmtr-5203d48b-lambda-basic-execution": {
        "policy_content": {
            "Statement": [
                {
                    "Action": [
                        "logs:CreateLogGroup",
                        "logs:CreateLogStream",
                        "logs:PutLogEvents",
                        "dynamodb:GetItem",
                        "dynamodb:Query",
                        "dynamodb:PutItem",
                        "dynamodb:Batch*",
                        "dynamodb:DeleteItem",
                        "ssm:PutParameter",
                        "ssm:GetParameter",
                        "kms:Decrypt"
                    ],
                    "Effect": "Allow",
                    "Resource": "*"
                }
            ],
            "Version": "2012-10-17"
        },
        "resource_type": "iam_policy"
    },
    "cmtr-5203d48b-task01-role": {
        "predefined_policies": [],
        "principal_service": "lambda",
        "custom_policies": [
            "cmtr-5203d48b-lambda-basic-execution"
        ],
        "resource_type": "iam_role",
        "permissions_boundary": "arn:aws:iam::196241772369:policy/eo_role_boundary"
    },
    "cmtr-5203d48b-task01": {
        "name": "cmtr-5203d48b-task01",
        "lambda_path": "/Users/Berkay_Buharali/Learn/AWS_Serverless/task01/BbAwsServerlessTask01",
        "version": "1.0.0",
        "func_name": "com.BbAwsServerlessTask01.Task01",
        "deployment_package": "BbAwsServerlessTask01-1.0.0.jar",
        "resource_type": "lambda",
        "runtime": "java11",
        "architectures": [
            "x86_64"
        ],
        "iam_role_name": "cmtr-5203d48b-task01-role",
        "memory": 1024,
        "timeout": 300,
        "subnet_ids": [],
        "security_group_ids": [],
        "dependencies": [],
        "event_sources": [],
        "env_variables": {},
        "publish_version": true,
        "alias": "dev",
        "logs_expiration": "30",
        "snap_start": "None",
        "prefix": "cmtr-5203d48b-",
        "suffix": "",
        "s3_path": "task01_240529.113359/BbAwsServerlessTask01-1.0.0.jar"
    }
}
2024-05-29 11:34:55,346 [DEBUG] USER:Berkay_Buharali deployment_processor.py:333:create_deployment_resources LOG: Going to create: {
    "cmtr-5203d48b-lambda-basic-execution": {
        "policy_content": {
            "Statement": [
                {
                    "Action": [
                        "logs:CreateLogGroup",
                        "logs:CreateLogStream",
                        "logs:PutLogEvents",
                        "dynamodb:GetItem",
                        "dynamodb:Query",
                        "dynamodb:PutItem",
                        "dynamodb:Batch*",
                        "dynamodb:DeleteItem",
                        "ssm:PutParameter",
                        "ssm:GetParameter",
                        "kms:Decrypt"
                    ],
                    "Effect": "Allow",
                    "Resource": "*"
                }
            ],
            "Version": "2012-10-17"
        },
        "resource_type": "iam_policy"
    },
    "cmtr-5203d48b-task01-role": {
        "predefined_policies": [],
        "principal_service": "lambda",
        "custom_policies": [
            "cmtr-5203d48b-lambda-basic-execution"
        ],
        "resource_type": "iam_role",
        "permissions_boundary": "arn:aws:iam::196241772369:policy/eo_role_boundary"
    },
    "cmtr-5203d48b-task01": {
        "name": "cmtr-5203d48b-task01",
        "lambda_path": "/Users/Berkay_Buharali/Learn/AWS_Serverless/task01/BbAwsServerlessTask01",
        "version": "1.0.0",
        "func_name": "com.BbAwsServerlessTask01.Task01",
        "deployment_package": "BbAwsServerlessTask01-1.0.0.jar",
        "resource_type": "lambda",
        "runtime": "java11",
        "architectures": [
            "x86_64"
        ],
        "iam_role_name": "cmtr-5203d48b-task01-role",
        "memory": 1024,
        "timeout": 300,
        "subnet_ids": [],
        "security_group_ids": [],
        "dependencies": [],
        "event_sources": [],
        "env_variables": {},
        "publish_version": true,
        "alias": "dev",
        "logs_expiration": "30",
        "snap_start": "None",
        "prefix": "cmtr-5203d48b-",
        "suffix": "",
        "s3_path": "task01_240529.113359/BbAwsServerlessTask01-1.0.0.jar"
    }
}
2024-05-29 11:34:55,346 [INFO] USER:Berkay_Buharali deployment_processor.py:345:create_deployment_resources LOG: Going to deploy AWS resources
2024-05-29 11:34:55,370 [DEBUG] USER:Berkay_Buharali iam_connection.py:51:__init__ LOG: Opened new IAM connection.
2024-05-29 11:34:55,380 [DEBUG] USER:Berkay_Buharali lambda_connection.py:59:__init__ LOG: Opened new Lambda connection.
2024-05-29 11:34:55,385 [DEBUG] USER:Berkay_Buharali s3_connection.py:45:__init__ LOG: Opened new S3 connection.
2024-05-29 11:34:55,423 [DEBUG] USER:Berkay_Buharali cloud_watch_connection.py:47:__init__ LOG: Opened new Cloudwatch logs connection.
2024-05-29 11:34:55,444 [DEBUG] USER:Berkay_Buharali dynamo_connection.py:112:__init__ LOG: Opened new DynamoDB connection.
2024-05-29 11:34:55,448 [DEBUG] USER:Berkay_Buharali sqs_connection.py:40:__init__ LOG: Opened new SQS connection.
2024-05-29 11:34:55,454 [DEBUG] USER:Berkay_Buharali kinesis_connection.py:41:__init__ LOG: Opened new Kinesis connection.
2024-05-29 11:34:55,461 [DEBUG] USER:Berkay_Buharali cloud_watch_connection.py:163:__init__ LOG: Opened new Cloudwatch events connection.
2024-05-29 11:34:55,467 [DEBUG] USER:Berkay_Buharali cloud_watch_connection.py:386:__init__ LOG: Opened new Cloudwatch metric connection.
2024-05-29 11:34:55,472 [DEBUG] USER:Berkay_Buharali application_autoscaling_connection.py:36:__init__ LOG: Opened new Application autoscaling connection.
2024-05-29 11:34:55,479 [DEBUG] USER:Berkay_Buharali api_gateway_connection.py:55:__init__ LOG: Opened new API Gateway connection.
2024-05-29 11:34:55,487 [DEBUG] USER:Berkay_Buharali cognito_identity_provider_connection.py:38:__init__ LOG: Opened new Cognito identity connection.
2024-05-29 11:34:55,492 [DEBUG] USER:Berkay_Buharali cognito_identity_connection.py:39:__init__ LOG: Opened new Cognito identity connection.
2024-05-29 11:34:55,494 [DEBUG] USER:Berkay_Buharali cloud_watch_connection.py:386:__init__ LOG: Opened new Cloudwatch metric connection.
2024-05-29 11:34:55,499 [DEBUG] USER:Berkay_Buharali sns_connection.py:36:__init__ LOG: Opened new SNS connection.
2024-05-29 11:34:55,530 [DEBUG] USER:Berkay_Buharali ec2_connection.py:60:__init__ LOG: Opened new EC2 connection.
2024-05-29 11:34:55,536 [DEBUG] USER:Berkay_Buharali elastic_beanstalk_connection.py:35:__init__ LOG: Opened new Elastic beanstalk connection.
2024-05-29 11:34:55,541 [DEBUG] USER:Berkay_Buharali step_functions_connection.py:37:__init__ LOG: Opened new Step Functions connection.
2024-05-29 11:34:55,546 [DEBUG] USER:Berkay_Buharali batch_connection.py:37:__init__ LOG: Opened new Batch connection.
2024-05-29 11:34:55,583 [DEBUG] USER:Berkay_Buharali documentdb_connection.py:39:__init__ LOG: Opened new DocumentDB connection.
2024-05-29 11:34:55,586 [DEBUG] USER:Berkay_Buharali dax_connection.py:34:__init__ LOG: Opened new DAX connection.
2024-05-29 11:34:55,590 [DEBUG] USER:Berkay_Buharali firehose_connection.py:20:__init__ LOG: Opened new Firehose connection.
2024-05-29 11:34:55,594 [DEBUG] USER:Berkay_Buharali eventbridge_scheduler_connection.py:20:__init__ LOG: Opened new EventBridge Scheduler connection.
2024-05-29 11:34:55,594 [INFO] USER:Berkay_Buharali deployment_processor.py:85:_process_resources LOG: Processing iam_policy resources
2024-05-29 11:34:56,259 [INFO] USER:Berkay_Buharali iam_resource.py:118:_create_policy_from_meta LOG: Created IAM policy cmtr-5203d48b-lambda-basic-execution.
2024-05-29 11:34:56,433 [INFO] USER:Berkay_Buharali deployment_processor.py:85:_process_resources LOG: Processing iam_role resources
2024-05-29 11:34:59,687 [INFO] USER:Berkay_Buharali iam_resource.py:178:_create_role_from_meta LOG: Created IAM role cmtr-5203d48b-task01-role.
2024-05-29 11:34:59,689 [INFO] USER:Berkay_Buharali deployment_processor.py:97:_process_resources LOG: Processing lambda resources
2024-05-29 11:34:59,689 [DEBUG] USER:Berkay_Buharali lambda_resource.py:260:_create_lambda_from_meta LOG: Creating lambda cmtr-5203d48b-task01
2024-05-29 11:34:59,808 [ERROR] USER:Berkay_Buharali deployment_processor.py:104:_process_resources LOG: Error occurred while lambda resource creating: Error while creating lambda: cmtr-5203d48b-task01;Deployment package 5203d48b/task01/task01_240529.113359/BbAwsServerlessTask01-1.0.0.jar does not exist in syndicate-education-platform-custom-sandbox-artifacts-sbox01 bucket
Traceback (most recent call last):
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/build/deployment_processor.py", line 99, in _process_resources
    response = func(args)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/resources/lambda_resource.py", line 161, in create_lambda
    return self.create_pool(self._create_lambda_from_meta, args)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/resources/base_resource.py", line 41, in create_pool
    result = future.result()
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/helper.py", line 66, in wrapper
    return handler_func(**parameters)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/connection/helper.py", line 91, in wrapper
    return handler_func(*args, **kwargs)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/resources/lambda_resource.py", line 271, in _create_lambda_from_meta
    raise AssertionError(f'Error while creating lambda: {name};'
AssertionError: Error while creating lambda: cmtr-5203d48b-task01;Deployment package 5203d48b/task01/task01_240529.113359/BbAwsServerlessTask01-1.0.0.jar does not exist in syndicate-education-platform-custom-sandbox-artifacts-sbox01 bucket
2024-05-29 11:34:59,937 [WARNING] USER:Berkay_Buharali deployment_processor.py:142:update_failed_output LOG: Unable to describe lambda resource with name cmtr-5203d48b-task01. Exception: 'NoneType' object is not subscriptable
2024-05-29 11:34:59,937 [INFO] USER:Berkay_Buharali deployment_processor.py:358:create_deployment_resources LOG: Going to create deploy output
2024-05-29 11:34:59,968 [WARNING] USER:Berkay_Buharali bundle_processor.py:57:create_deploy_output LOG: Output file for deploy task01 already exists.
2024-05-29 11:34:59,969 [INFO] USER:Berkay_Buharali deployment_processor.py:364:create_deployment_resources LOG: Deploy output for task01 was created.
2024-05-29 11:34:59,969 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage deploy, elapsed time: 0:00:04.662826
2024-05-29 11:35:00,055 [DEBUG] USER:Berkay_Buharali sync_processor.py:38:sync_project_state LOG: Syncing with remote .syndicate file.
2024-05-29 11:35:00,120 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:35:00,120 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:35:00,120 [DEBUG] USER:Berkay_Buharali sync_processor.py:41:sync_project_state LOG: Actualizing the project state...
2024-05-29 11:35:00,137 [DEBUG] USER:Berkay_Buharali sync_processor.py:46:sync_project_state LOG: Saving a local .syndicate file.
2024-05-29 11:35:00,152 [DEBUG] USER:Berkay_Buharali sync_processor.py:49:sync_project_state LOG: Synced the .syndicate file. Pushing...
2024-05-29 11:35:00,238 [DEBUG] USER:Berkay_Buharali sync_processor.py:51:sync_project_state LOG: Push successful
2024-05-29 11:35:00,238 [DEBUG] USER:Berkay_Buharali sync_processor.py:52:sync_project_state LOG: Remote .syndicate file pulled
2024-05-29 11:35:00,238 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:45:27,034 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:45:27,233 [INFO] USER:Berkay_Buharali bundle_processor.py:207:create_bundles_bucket LOG: Bundles bucket syndicate-education-platform-custom-sandbox-artifacts-sbox01 already exists
2024-05-29 11:45:27,233 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage create_deploy_target_bucket, elapsed time: 0:00:00.198792
2024-05-29 11:45:38,438 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:45:38,831 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage test, elapsed time: 0:00:00.000280
2024-05-29 11:45:38,852 [INFO] USER:Berkay_Buharali project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/jsrc/main/java/com/task01.
2024-05-29 11:45:38,852 [INFO] USER:Berkay_Buharali project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/src/lambdas.
2024-05-29 11:45:38,852 [INFO] USER:Berkay_Buharali project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/app/lambdas.
2024-05-29 11:45:38,852 [INFO] USER:Berkay_Buharali project_state.py:331:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/swagger_src.
2024-05-29 11:45:38,852 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage assemble, elapsed time: 0:00:00.000331
2024-05-29 11:45:38,872 [INFO] USER:Berkay_Buharali meta_processor.py:483:create_meta LOG: Bundle path: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/bundles/task01_240529.114538
2024-05-29 11:45:38,874 [INFO] USER:Berkay_Buharali helper.py:299:write_content_to_file LOG: /Users/Berkay_Buharali/Learn/AWS_Serverless/task01/.syndicate-config-dev/bundles/task01_240529.114538/build_meta.json file was created.
2024-05-29 11:45:38,874 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage package_meta, elapsed time: 0:00:00.002919
2024-05-29 11:45:39,007 [INFO] USER:Berkay_Buharali bundle_processor.py:185:upload_bundle_to_s3 LOG: Bundle was validated successfully
2024-05-29 11:45:39,097 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage upload, elapsed time: 0:00:00.160425
2024-05-29 11:45:39,116 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage build, elapsed time: 0:00:00.544206
2024-05-29 11:45:49,025 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:45:49,301 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:45:49,302 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:45:49,477 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:45:49,477 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: task01
2024-05-29 11:45:49,585 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:45:49,585 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:45:49,711 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:45:49,711 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: task01_240529.114538
2024-05-29 11:45:49,826 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:45:49,826 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:45:49,945 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:45:50,070 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:45:50,070 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:45:50,203 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:45:50,384 [ERROR] USER:Berkay_Buharali helper.py:84:wrapper LOG: An error occurred. See details in the log file
2024-05-29 11:45:50,385 [ERROR] USER:Berkay_Buharali helper.py:85:wrapper LOG: Error occurred: Deployment output file not found. It might be because the previous deployment failed. If this is the case deployment can be continued by using the command  'syndicate deploy --continue_deploy' or failed deployed resources can be removed with the command 'syndicate clean --rollback'
Traceback (most recent call last):
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/build/bundle_processor.py", line 140, in load_latest_deploy_output
    return load_deploy_output(bundle_name, deploy_name)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/build/bundle_processor.py", line 111, in load_deploy_output
    raise AssertionError('Deploy name {0} does not exist.'
AssertionError: Deploy name task01 does not exist. Cannot find output file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/helper.py", line 82, in wrapper
    return handler_func(*args, **kwargs)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/build/deployment_processor.py", line 298, in create_deployment_resources
    latest_deploy_output = load_latest_deploy_output()
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/build/bundle_processor.py", line 143, in load_latest_deploy_output
    raise AssertionError(
AssertionError: Deployment output file not found. It might be because the previous deployment failed. If this is the case deployment can be continued by using the command  'syndicate deploy --continue_deploy' or failed deployed resources can be removed with the command 'syndicate clean --rollback'
2024-05-29 11:45:50,527 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:45:50,527 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:45:50,658 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:46:11,366 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:46:11,695 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:46:11,695 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:46:11,861 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:46:11,862 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: task01
2024-05-29 11:46:11,979 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:46:11,979 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:46:12,097 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:46:12,097 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: task01_240529.114538
2024-05-29 11:46:12,208 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:46:12,208 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:46:12,326 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:46:12,453 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:46:12,454 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:46:12,590 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:46:12,776 [ERROR] USER:Berkay_Buharali helper.py:84:wrapper LOG: An error occurred. See details in the log file
2024-05-29 11:46:12,776 [ERROR] USER:Berkay_Buharali helper.py:85:wrapper LOG: Error occurred: Deploy name task01 does not exist. Cannot find output file.
Traceback (most recent call last):
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/helper.py", line 82, in wrapper
    return handler_func(*args, **kwargs)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/build/deployment_processor.py", line 501, in continue_deployment_resources
    output = load_failed_deploy_output(bundle_name, deploy_name)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/build/bundle_processor.py", line 129, in load_failed_deploy_output
    raise AssertionError('Deploy name {0} does not exist.'
AssertionError: Deploy name task01 does not exist. Cannot find output file.
2024-05-29 11:46:12,916 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:46:12,917 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:46:13,051 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:46:23,788 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:46:24,016 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:46:24,016 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:46:24,144 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:46:24,144 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: task01
2024-05-29 11:46:24,248 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:46:24,248 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:46:24,366 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:46:24,366 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: task01_240529.114538
2024-05-29 11:46:24,471 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:46:24,471 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:46:24,590 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:46:24,704 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:46:24,704 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:46:24,842 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:46:25,057 [ERROR] USER:Berkay_Buharali helper.py:84:wrapper LOG: An error occurred. See details in the log file
2024-05-29 11:46:25,057 [ERROR] USER:Berkay_Buharali helper.py:85:wrapper LOG: Error occurred: Deployment output file not found. It might be because the previous deployment failed. If this is the case deployment can be continued by using the command  'syndicate deploy --continue_deploy' or failed deployed resources can be removed with the command 'syndicate clean --rollback'
Traceback (most recent call last):
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/build/bundle_processor.py", line 140, in load_latest_deploy_output
    return load_deploy_output(bundle_name, deploy_name)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/build/bundle_processor.py", line 111, in load_deploy_output
    raise AssertionError('Deploy name {0} does not exist.'
AssertionError: Deploy name task01 does not exist. Cannot find output file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/helper.py", line 82, in wrapper
    return handler_func(*args, **kwargs)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/build/deployment_processor.py", line 298, in create_deployment_resources
    latest_deploy_output = load_latest_deploy_output()
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/build/bundle_processor.py", line 143, in load_latest_deploy_output
    raise AssertionError(
AssertionError: Deployment output file not found. It might be because the previous deployment failed. If this is the case deployment can be continued by using the command  'syndicate deploy --continue_deploy' or failed deployed resources can be removed with the command 'syndicate clean --rollback'
2024-05-29 11:46:25,186 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:46:25,186 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:46:25,304 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:46:34,317 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:46:34,580 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:46:34,580 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:46:34,739 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:46:34,739 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: task01
2024-05-29 11:46:34,850 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:46:34,850 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:46:34,996 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:46:34,996 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: task01_240529.113359
2024-05-29 11:46:35,099 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:46:35,099 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:46:35,212 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:46:35,343 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:46:35,343 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:46:35,487 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:46:35,582 [INFO] USER:Berkay_Buharali deployment_processor.py:564:remove_failed_deploy_resources LOG: Failed output file was loaded successfully
2024-05-29 11:46:35,582 [INFO] USER:Berkay_Buharali deployment_processor.py:568:remove_failed_deploy_resources LOG: Prefixes and suffixes of any resource names have been resolved.
2024-05-29 11:46:35,582 [INFO] USER:Berkay_Buharali deployment_processor.py:597:remove_failed_deploy_resources LOG: Going to clean AWS resources
2024-05-29 11:46:35,582 [INFO] USER:Berkay_Buharali deployment_processor.py:176:clean_resources LOG: Removing iam_role resources ...
2024-05-29 11:46:38,036 [INFO] USER:Berkay_Buharali iam_resource.py:82:_remove_role LOG: IAM role cmtr-5203d48b-task01-role was removed.
2024-05-29 11:46:38,037 [INFO] USER:Berkay_Buharali deployment_processor.py:183:clean_resources LOG: Removing iam_policy resources ...
2024-05-29 11:46:38,407 [INFO] USER:Berkay_Buharali iam_resource.py:46:_remove_policy LOG: IAM policy cmtr-5203d48b-lambda-basic-execution was removed.
2024-05-29 11:46:38,479 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage clean, elapsed time: 0:00:02.991949
2024-05-29 11:46:38,558 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:46:38,559 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:46:38,821 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:46:38,821 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:46:38,952 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:46:45,444 [INFO] USER:Berkay_Buharali processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2024-05-29 11:46:45,660 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:46:45,661 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:46:45,785 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:46:45,786 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of deploy_name: task01
2024-05-29 11:46:45,888 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:46:45,888 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:46:46,008 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:46:46,008 [INFO] USER:Berkay_Buharali helper.py:240:resolve_default_value LOG: Resolved value of bundle_name: task01_240529.114538
2024-05-29 11:46:46,112 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:46:46,112 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:46:46,228 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:46:46,364 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:46:46,364 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:46:46,519 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2024-05-29 11:46:46,698 [INFO] USER:Berkay_Buharali deployment_processor.py:312:create_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved.
2024-05-29 11:46:46,698 [INFO] USER:Berkay_Buharali deployment_processor.py:345:create_deployment_resources LOG: Going to deploy AWS resources
2024-05-29 11:46:46,899 [INFO] USER:Berkay_Buharali deployment_processor.py:85:_process_resources LOG: Processing iam_policy resources
2024-05-29 11:46:47,540 [INFO] USER:Berkay_Buharali iam_resource.py:118:_create_policy_from_meta LOG: Created IAM policy cmtr-5203d48b-lambda-basic-execution.
2024-05-29 11:46:47,686 [INFO] USER:Berkay_Buharali deployment_processor.py:85:_process_resources LOG: Processing iam_role resources
2024-05-29 11:46:50,798 [INFO] USER:Berkay_Buharali iam_resource.py:178:_create_role_from_meta LOG: Created IAM role cmtr-5203d48b-task01-role.
2024-05-29 11:46:50,799 [INFO] USER:Berkay_Buharali deployment_processor.py:97:_process_resources LOG: Processing lambda resources
2024-05-29 11:46:50,957 [ERROR] USER:Berkay_Buharali deployment_processor.py:104:_process_resources LOG: Error occurred while lambda resource creating: Error while creating lambda: cmtr-5203d48b-task01;Deployment package 5203d48b/task01/task01_240529.114538/BbAwsServerlessTask01-1.0.0.jar does not exist in syndicate-education-platform-custom-sandbox-artifacts-sbox01 bucket
Traceback (most recent call last):
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/build/deployment_processor.py", line 99, in _process_resources
    response = func(args)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/resources/lambda_resource.py", line 161, in create_lambda
    return self.create_pool(self._create_lambda_from_meta, args)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/resources/base_resource.py", line 41, in create_pool
    result = future.result()
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/helper.py", line 66, in wrapper
    return handler_func(**parameters)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/connection/helper.py", line 91, in wrapper
    return handler_func(*args, **kwargs)
  File "/Users/Berkay_Buharali/.pyenv/versions/3.10.4/lib/python3.10/site-packages/syndicate/core/resources/lambda_resource.py", line 271, in _create_lambda_from_meta
    raise AssertionError(f'Error while creating lambda: {name};'
AssertionError: Error while creating lambda: cmtr-5203d48b-task01;Deployment package 5203d48b/task01/task01_240529.114538/BbAwsServerlessTask01-1.0.0.jar does not exist in syndicate-education-platform-custom-sandbox-artifacts-sbox01 bucket
2024-05-29 11:46:51,142 [WARNING] USER:Berkay_Buharali deployment_processor.py:142:update_failed_output LOG: Unable to describe lambda resource with name cmtr-5203d48b-task01. Exception: 'NoneType' object is not subscriptable
2024-05-29 11:46:51,142 [INFO] USER:Berkay_Buharali deployment_processor.py:358:create_deployment_resources LOG: Going to create deploy output
2024-05-29 11:46:51,315 [INFO] USER:Berkay_Buharali bundle_processor.py:63:create_deploy_output LOG: Output file with name task01_240529.114538/outputs/task01_failed.json has been created
2024-05-29 11:46:51,316 [INFO] USER:Berkay_Buharali deployment_processor.py:364:create_deployment_resources LOG: Deploy output for task01 was created.
2024-05-29 11:46:51,316 [INFO] USER:Berkay_Buharali helper.py:336:timed LOG: Stage deploy, elapsed time: 0:00:04.654237
2024-05-29 11:46:51,500 [INFO] USER:Berkay_Buharali project_state.py:117:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2024-05-29 11:46:51,500 [INFO] USER:Berkay_Buharali project_state.py:122:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2024-05-29 11:46:51,624 [INFO] USER:Berkay_Buharali sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
